// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"AcmeTest/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreatePetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// unexpected error
	Error *shared.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
